version: 2.1
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
  test:
    working_directory: ~/app
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: unit test
          command: npm run test

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
      - test:
          requires:
            - build
          filters:
            branches:
              only: develop
